const num:number=123
document.title='TypeScript'
// import './example/basic-typs'
// import './example/symbol'
// import './example/interface'
// import './example/function'
// import './example/generics'
// import './example/es6_class_1'
// import './example/es6_class_2'
// import './example/class'
// import './example/enum'
// import './example/interence-compatibility'
// import './example/advanced-type-1'
// import './example/advanced-type-2'
// import './modules/index'
// import './ts-modules/index'
// import './example/merging'
// import './example/decorators'
// import './example/mixin'
import './example/update'
// import './example/declaration-files'